_target_: src.models.gaze_module.GazeLitModule

loss_type: l1
single_mix: false
double_head: false
weight_ce: false
weight_cs: false
num_chunks: ${num_chunks}
compile: true

optimizer:
  _target_: src.models.optims.create_optimizer
  _partial_: true
  opt:
    _target_: torch.optim.Adam
    _partial_: true
    betas:
      - 0.9
      - 0.999
  lr: 0.0001
  weight_decay: 0.000001


scheduler: null
  # Example: StepLR
  # _target_: torch.optim.lr_scheduler.StepLR
  # _partial_: true
  # step_size: 10
  # gamma: 0.1

net:
  _target_: src.models.components.gaze.GazeModel
  model_name: null
  pretrained: true
  num_chunks: ${num_chunks}
  head_func: 
    _target_: torch.nn.Linear
    _partial_: true
