# @package _global_

defaults:
  - _self_
  - data: gaze # choose datamodule with `test_dataloader()` for evaluation
  - model: gaze
  - logger: null
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"
num_chunks: 2
tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ???
